### ISSUE TITLE
Project's folder structure 

### ISSUE THREAD

**Issue by Karyum** [webAhead1/node-js-project1#3]
Let's move whatever is in the workshop folder into the root folder of the project (since this is a project and a workshop 😅), this will break the start script in your `package.json` so you will also need to change that.

Also the `.env` file is not supposed to show in the project, it's supposed to be a 'secret' file hidden through the `.gitignore` file, to remove it you might need to do the following:
 - Copy the contents of the file
 - Delete the file
 - git add & commit the file change
 - then add the file to the `.gitignore` file

**Comment by Asmaalafe55** [comment]
we already did it before your comment.
