### ISSUE TITLE
Add your details page 

### ISSUE THREAD

**Issue by Nur1995** [webAhead1/node-js-project1#6]
**Templates.js**
Negative value for age input 
You can add min="18" (or whatever minimum age you'd like) in the age input tag
You can also add a maximum age, same logic. 
https://github.com/webAhead1/node-js-project1/blob/de9b3025722d9a6a185fc49b91b122000ed7abe4/workshop/templates.js#L110

**Just a suggestion, to keep everything consistent, take out the "Your" next to "Name" and "Age." So it'll just be
Name
Age
Height
Weight

**Server.js**
Height/Weight - add units (feet+inches/lb or meters/kg)
- which also contributes to your existing "length" issue, where it can easily be confused with row.length. Changing length to height (other than rows.length) will help clear up some confusion.

**Comment by Asmaalafe55** [comment]
done
